version: "3"
services:
  postgres:
    image: postgres:latest
    network_mode: bridge
    container_name: postgresx
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5434
    ports:
      - 5434:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=employee
    restart: unless-stopped
  # APP*****************************************
  springbootappy:
    image: springbootappy:latest
    network_mode: bridge
    container_name: springbootappy
    expose:
      - 8081
    ports:
      - 8081:9090 #map port 9090 to port 8080
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
volumes:
  postgres-data: